### ISSUE TITLE
在tomcat也支持nio的模式下，对比性能真的有提升吗？

### ISSUE THREAD

**Issue by WTroy** [farsunset/netty-http-server#2]
1. 我是用jmeter测试了一下，在1秒内发送1w个请求，只返回“hello world”，平均响应时间比直接使用tomcat满了1s，而且异常率也高一些，不知道使我测试方法的问题还是其它原因？
2. 还有一点HttpServerHandler.class中 在处理http的时候 为什么还要用到线程池？不是Netty的两个group本身就是主从线程组，这一点我也没理解，请大佬解惑！
- btw：打包后 体积确实减少很多！

**Comment by farsunset** [comment]
tomcat是包含了 java ee的一系列组件，netty 做服务端更适合做和页面无关的接口服务，或者网关服务，所以更轻量级，IO密集型服务，线程池需要调整适当高一些

**Comment by WTroy** [comment]
第二个问题呢，我做了测试 不使用线程池，直接操作也是没问题。netty serverbootstrap 本身就有两个eventgroup，workeventgroup我理解本身就是后台channel操作所依赖的线程。
我是刚学习netty，可能理解上有问题，望勿见怪，请指正。

**Comment by farsunset** [comment]
2层线程池是因为如果你的http接口比较耗时导致workeventgroup队列占满 就会出现停止服务，多加一层是降低概率，但是依然无法完全避免这种情况

**Comment by WTroy** [comment]
GET 多谢，学习了！
